server:
  application:
    name: QuanLyKhoNhot
  port: 8386

spring:
  datasource:
    url: yeume-enterprise.edu.vn
    username: yeumeent_czmn
    password: concakgi@123
    port: 3306
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Cái này có th? t?t ?i nha nó s? hi?n câu truy v?n sql ? trong terminal

